# Domain name for Kong ingress routes and TLS
variable "domain_name" {
  description = "Domain name for Kong Ingress routes and ACM certificate lookup"
  type        = string
}

# JWT signing secret for API authentication
variable "jwt_secret" {
  description = "JWT signing secret (auto-generated by Terraform, stored in AWS SM)"
  type        = string
  sensitive   = true
  default     = ""
}
