sonar.projectKey=online-boutique-cartservice
sonar.projectName=Online Boutique — CartService
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/obj/**,**/bin/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-cartservice
