sonar.projectKey=online-boutique-shippingservice
sonar.projectName=Online Boutique — ShippingService
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/genproto/**,**/proto/**,**/*.pb.go,**/vendor/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-shippingservice
