sonar.projectKey=online-boutique-emailservice
sonar.projectName=Online Boutique — EmailService
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/genproto/**,**/proto/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-emailservice
