sonar.projectKey=online-boutique-recommendationservice
sonar.projectName=Online Boutique — RecommendationService
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/__pycache__/**,**/genproto/**,**/proto/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-recommendationservice
