sonar.projectKey=online-boutique-paymentservice
sonar.projectName=Online Boutique — PaymentService
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/genproto/**,**/proto/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-paymentservice
