sonar.projectKey=online-boutique-adservice
sonar.projectName=Online Boutique — AdService
sonar.projectVersion=1.0.0
sonar.sources=src
sonar.exclusions=**/gradle/**,**/build/**,**/genproto/**,**/proto/**
sonar.java.binaries=build/classes
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-adservice
