sonar.projectKey=online-boutique-frontend
sonar.projectName=Online Boutique — Frontend
sonar.projectVersion=1.0.0
sonar.sources=.
sonar.exclusions=**/node_modules/**,**/genproto/**,**/proto/**
sonar.sourceEncoding=UTF-8
sonar.working.directory=/tmp/.scannerwork-frontend
