"""
Release Notes Agent — Generates release notes from git commits.
Summarizes changes, categorizes by type, and creates human-readable changelog.

Usage in pipeline:
  python release_notes_agent.py
  python release_notes_agent.py --commits 10
"""

import argparse
import os
import subprocess
import sys
from ai_provider import get_ai_response


def get_recent_commits(count=10):
    """Get recent git commits"""
    try:
        # Set safe directory for Harness workspace
        subprocess.run(["git", "config", "--global", "--add", "safe.directory", "/harness"], capture_output=True, timeout=5)
        # Fetch git history (Harness uses shallow clone)
        subprocess.run(["git", "-C", "/harness", "fetch", "--unshallow"], capture_output=True, timeout=30)
        result = subprocess.run(
            ["git", "-C", "/harness", "log", f"-{count}", "--pretty=format:%h|%s|%an|%ad", "--date=short"],
            capture_output=True, text=True, timeout=10
        )
        if result.returncode == 0 and result.stdout.strip():
            return result.stdout
        return None
    except (subprocess.TimeoutExpired, FileNotFoundError):
        return None


def generate_release_notes(commits):
    """Send commits to AI and generate release notes"""
    prompt = f"""You are a technical writer generating release notes for a microservices platform deployment.

## Recent Commits:
{commits}

Generate professional release notes with:
1. **RELEASE SUMMARY** (2-3 sentences about what this release contains)
2. **CONTRIBUTORS** (list each author with their commit count and what they worked on)
3. **COMMIT DETAILS** (table: hash | message | author | date)
4. **NEW FEATURES** (bullet points)
5. **BUG FIXES** (bullet points)
6. **IMPROVEMENTS** (bullet points)
7. **BREAKING CHANGES** (if any)
8. **SECURITY UPDATES** (if any)
9. **DEPLOYMENT STATS** (total commits, date range, number of unique contributors)

Format: Clean markdown. Skip empty sections. Be concise but detailed."""

    print("=" * 60)
    print("  📝 AI RELEASE NOTES AGENT")
    print("=" * 60)
    print()

    response = get_ai_response(prompt)
    print(response)

    print()
    print("=" * 60)
    print("  Release notes generated by AI Agent")
    print("=" * 60)

    return response


def main():
    parser = argparse.ArgumentParser(description="AI Release Notes Agent")
    parser.add_argument("--commits", type=int, default=10, help="Number of commits to analyze")
    args = parser.parse_args()

    print("📝 Release Notes Agent starting...")
    print()

    commits = get_recent_commits(args.commits)

    if not commits:
        print("⚠️  No git commits found.")
        return

    print(f"  Analyzing last {args.commits} commits...")
    print()

    generate_release_notes(commits)


if __name__ == "__main__":
    main()
