apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
  namespace: {{.Values.namespace}}
  labels:
    app: cartservice
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: cartservice
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
        - name: cartservice
          image: {{.Values.cartserviceImage}}
          ports:
            - containerPort: 7070
          envFrom:
            - secretRef:
                name: app-secrets # COLLECTOR_SERVICE_ADDR, REDIS_ADDR from AWS SM
            - secretRef:
                name: db-credentials
          resources:
            requests:
              cpu: 200m
              memory: 64Mi
            limits:
              cpu: 300m
              memory: 128Mi
          readinessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 7070
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: cartservice
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: cartservice
  ports:
    - port: 7070
      targetPort: 7070
