apiVersion: v1
kind: Namespace
metadata:
  name: {{.Values.namespace}}
  labels:
    app: online-boutique
    environment: production
    managed-by: harness-gitops
    episode: "10"
    monitoring: enabled
