apiVersion: apps/v1
kind: Deployment
metadata:
  name: recommendationservice
  namespace: {{.Values.namespace}}
  labels:
    app: recommendationservice
spec:
  replicas: {{int .Values.replicas}}
  selector:
    matchLabels:
      app: recommendationservice
  template:
    metadata:
      labels:
        app: recommendationservice
    spec:
      containers:
        - name: recommendationservice
          image: {{.Values.recommendationserviceImage}}
          ports:
            - containerPort: 8080
          env:
            - name: PORT
              value: "8080"
            - name: PRODUCT_CATALOG_SERVICE_ADDR
              value: "productcatalogservice:3550"
          envFrom:
            - secretRef:
                name: db-credentials
          resources:
            requests:
              cpu: 100m
              memory: 220Mi
            limits:
              cpu: 200m
              memory: 450Mi
          readinessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            grpc:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: recommendationservice
  namespace: {{.Values.namespace}}
spec:
  type: ClusterIP
  selector:
    app: recommendationservice
  ports:
    - port: 8080
      targetPort: 8080
