frontendImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/frontend:v2
cartserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/cartservice:v2
checkoutserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/checkoutservice:v2
productcatalogserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/productcatalogservice:v2
currencyserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/currencyservice:v2
emailserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/emailservice:v2
paymentserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/paymentservice:v2
recommendationserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/recommendationservice:v2
shippingserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/shippingservice:v2
adserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/adservice:v2
loadgeneratorImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/loadgenerator:v2
namespace: online-boutique
replicas: 2
domain: CHANGE-TO-YOUR-DOMAIN.com
enableTracing: '1'
loadgeneratorUsers: '10'
loadgeneratorSpawnRate: '1'
