frontendImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/frontend:v7
cartserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/cartservice:v7
checkoutserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/checkoutservice:v7
productcatalogserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/productcatalogservice:v7
currencyserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/currencyservice:v7
emailserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/emailservice:v7
paymentserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/paymentservice:v7
recommendationserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/recommendationservice:v7
shippingserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/shippingservice:v7
adserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/adservice:v7
loadgeneratorImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/loadgenerator:v7
namespace: online-boutique
replicas: 2
domain: CHANGE-TO-YOUR-DOMAIN.com
enableTracing: '1'
loadgeneratorUsers: '10'
loadgeneratorSpawnRate: '1'
