frontendImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/frontend:v1
cartserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/cartservice:v1
checkoutserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/checkoutservice:v1
productcatalogserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/productcatalogservice:v1
currencyserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/currencyservice:v1
emailserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/emailservice:v1
paymentserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/paymentservice:v1
recommendationserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/recommendationservice:v1
shippingserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/shippingservice:v1
adserviceImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/adservice:v1
loadgeneratorImage: 713939171080.dkr.ecr.us-east-1.amazonaws.com/loadgenerator:v1
namespace: online-boutique
replicas: 2
domain: CHANGE-TO-YOUR-DOMAIN.com
enableTracing: '1'
collectorServiceAddr: otel-collector.tracing.svc.cluster.local:4317
loadgeneratorUsers: '10'
loadgeneratorSpawnRate: '1'
